version: "3.8"

services:
  catalogue:
    build:
      context: .
      dockerfile: ./docker/catalogue/Dockerfile
    image: f3lin/catalogue:${TAG} # Use dynamic tag
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - reschedule=on-node-failure
    ports:
      - "80:8080"
    depends_on:
      catalogue-db:
        condition: service_healthy
    networks:
      - NETWORKS

  catalogue-db:
    build:
      context: ./docker/catalogue-db/
      dockerfile: Dockerfile
    image: f3lin/catalogue-db:${TAG} # Use dynamic tag
    hostname: catalogue-db
    restart: always
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-fake_password}
      - MYSQL_DATABASE=socksdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - NETWORKS

networks:
    NETWORKS:
        driver: bridge
