name: Test new Implementation
on:
  push:
    branches: [ dev ]

jobs:
  build:
    permissions:
      contents: write
    defaults:
      run:
        working-directory: go/src/github.com/exam-rncp/catalogue
    runs-on: ubuntu-latest
    env:
      GROUP: f3lin
      COMMIT: ${{ github.sha }}
      REPO: catalogue
      REPO_DB: catalogue-db
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/catalogue/catalogue/go/

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: go/src/github.com/exam-rncp/catalogue

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup PATH
        run: echo "${GOPATH}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: go get -u github.com/FiloSottile/gvt && gvt restore

      - name: Build
        run: |
          go test -v

      - name: Container Tests
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run:  |
          make test-unit
          make test-container
  
      - name: Docker images tag
        run: |
          docker image tag $GROUP/$REPO:v0.0 $GROUP/$REPO:$COMMIT
          docker image tag $GROUP/$REPO_DB:v0.0 $GROUP/$REPO_DB:$COMMIT
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.GROUP }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate Docker Compose File
        run: |
          NETWORK_NAME="network_$(git rev-parse --short HEAD || date +%s)"
          cp docker-compose.yml docker-compose.temp.yml
          sed -i "s/\NETWORKS/$NETWORK_NAME/g" docker-compose.temp.yml
          sed -i "s/\${TAG}/$TAG/g" docker-compose.temp.yml
          chmod 644 docker-compose.temp.yml

      - name: Run Docker Compose
        id: docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.temp.yml"
        continue-on-error: false

      - name: Checking application health...
        run: |
          docker exec catalogue-catalogue-1  wget -qO-  http://localhost:8080/health | jq .
          if [ $? -ne 0 ]; then
            echo "Health check failed"
            exit 1
          fi